from pathlib import Path
from typing import Any, Dict
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from templates.base import DocumentBuilder

class NCDBuilder(DocumentBuilder):
    """
    Assembles the final .docx using the NCD-specific template and styling.
    """
    def __init__(self):
        self.doc = Document()
        self._setup_styles()

    def _setup_styles(self):
        """Initializes NCD specific styles, fonts, and headers."""
        style = self.doc.styles['Normal']
        font = style.font
        font.name = 'Arial'
        font.size = Pt(11)
        # Note: In a production scenario, you would also load logo assets 
        # from templates/ncd/assets/ here.

    def add_cover_page(self, title: str = "User Manual"):
        """FR-37: Produces the cover page per NCD client format."""
        self.doc.add_heading("National Cooperative Database (NCD)", 0)
        title_para = self.doc.add_paragraph(title)
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        self.doc.add_paragraph("Silver Touch Technologies Ltd.")
        self.doc.add_page_break()

    def add_revision_history(self):
        """FR-37: Adds a revision history table."""
        self.doc.add_heading("Revision History", level=1)
        table = self.doc.add_table(rows=2, cols=4)
        table.style = 'Table Grid'
        
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Date'
        hdr_cells[1].text = 'Version'
        hdr_cells[2].text = 'Description'
        hdr_cells[3].text = 'Author'
        
        # Initial draft entry
        row_cells = table.rows[1].cells
        row_cells[0].text = '2026-07-03'
        row_cells[1].text = '1.0'
        row_cells[2].text = 'Initial Draft generated by Bot'
        row_cells[3].text = 'Documentation Team'
        
        self.doc.add_page_break()

    def add_toc_placeholder(self):
        """
        FR-37 & FR-41: Adds a placeholder for the Table of Contents.
        Word handles dynamic TOCs via fields, so we prompt the user to refresh it.
        """
        self.doc.add_heading("Table of Contents", level=1)
        self.doc.add_paragraph("[Right-click and select 'Update Field' in Word to generate TOC]")
        self.doc.add_page_break()

    def add_screen_section(self, screen_index: int, image_path: Path, content_data: Dict[str, Any]):
        """
        FR-38, FR-39, FR-40: Inserts the annotated PNG, procedure prose, 
        and field description table.
        """
        # Section Heading
        self.doc.add_heading(f"{screen_index}. Screen {screen_index} Interface", level=1)
        
        # Figure / Image Insertion
        if image_path.exists():
            self.doc.add_picture(str(image_path), width=Inches(6.0))
            cap = self.doc.add_paragraph(f"Figure {screen_index}: Screen {screen_index} View")
            cap.alignment = WD_ALIGN_PARAGRAPH.CENTER
            cap.style = 'Caption'

        # Procedure Prose
        prose = content_data.get("procedure_prose", "")
        if prose:
            self.doc.add_heading("Procedure Steps", level=2)
            self.doc.add_paragraph(prose)
            
        # Field Description Table
        fields = content_data.get("field_descriptions", [])
        if fields:
            self.doc.add_heading("Field Details", level=2)
            table = self.doc.add_table(rows=1, cols=2)
            table.style = 'Table Grid'
            
            hdr_cells = table.rows[0].cells
            hdr_cells[0].text = 'Field Name'
            hdr_cells[1].text = 'Description'
            
            for field in fields:
                row_cells = table.add_row().cells
                row_cells[0].text = field.get("field_name", "Unnamed")
                row_cells[1].text = field.get("description", "")
        
        self.doc.add_page_break()

    def save(self, output_path: Path):
        """Saves the assembled .docx to disk."""
        self.doc.save(output_path)