from pathlib import Path
from typing import Any, Dict
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from templates.base import DocumentBuilder

def hex_to_rgb(hex_str: str) -> RGBColor:
    """Helper to convert a hex color string to docx RGBColor."""
    hex_str = hex_str.lstrip('#')
    if len(hex_str) != 6:
        # Default back to a dark slate
        return RGBColor(27, 54, 93)
    return RGBColor(*(int(hex_str[i:i+2], 16) for i in (0, 2, 4)))

class CorporateBuilder(DocumentBuilder):
    """
    Assembles a highly professional, corporate-styled manual.
    All fonts, colors, and layout elements adapt dynamically to user preferences.
    """
    def __init__(self, style_config: Dict[str, Any] = None):
        super().__init__(style_config)

    def _setup_styles(self):
        """Initializes custom font family and base normal styles."""
        self.set_margins(1.0, 1.0, 1.0, 1.0)
        
        # Read styling configurations
        self.font_name = self.style_config.get("font_name", "Segoe UI")
        self.primary_hex = self.style_config.get("primary_color", "1B365D").lstrip('#')
        self.secondary_hex = self.style_config.get("secondary_color", "D97706").lstrip('#')
        self.text_hex = self.style_config.get("text_color", "333333").lstrip('#')
        
        # Set normal style font to user font
        style = self.doc.styles['Normal']
        font = style.font
        font.name = self.font_name
        font.size = Pt(10.5)
        font.color.rgb = hex_to_rgb(self.text_hex)
        
        # Set Heading styles to user font
        for heading_name in ['Heading 1', 'Heading 2', 'Heading 3']:
            if heading_name in self.doc.styles:
                h_style = self.doc.styles[heading_name]
                h_style.font.name = self.font_name
                h_style.font.color.rgb = hex_to_rgb(self.primary_hex)

    def add_cover_page(self, title: str = "User Manual"):
        """Generates a premium corporate cover page with dynamic logo and details."""
        # Top space
        for _ in range(2):
            self.doc.add_paragraph()
            
        # Optional Logo insertion
        logo_val = self.style_config.get("logo_path", "")
        logo_path = Path(logo_val) if logo_val else None
        if logo_path and logo_path.exists():
            p_logo = self.doc.add_paragraph()
            p_logo.alignment = WD_ALIGN_PARAGRAPH.LEFT
            p_logo.add_run().add_picture(str(logo_path), height=Inches(0.9))
            
        # Spacing
        for _ in range(2):
            self.doc.add_paragraph()

        # Company / Org subtitle (in uppercase, secondary color)
        company_name = self.style_config.get("company_name", "Corporate Corporation").upper()
        p_comp = self.doc.add_paragraph()
        run_comp = p_comp.add_run(company_name)
        run_comp.font.name = self.font_name
        run_comp.font.size = Pt(10.5)
        run_comp.font.bold = True
        run_comp.font.color.rgb = hex_to_rgb(self.secondary_hex)

        # Title
        p_title = self.doc.add_paragraph()
        run_title = p_title.add_run(title)
        run_title.font.name = self.font_name
        run_title.font.size = Pt(28)
        run_title.font.bold = True
        run_title.font.color.rgb = hex_to_rgb(self.primary_hex)
        
        # Draw bottom thick horizontal accent line
        self.add_bottom_border_to_paragraph(p_title, color_hex=self.primary_hex, sz=18)

        # Subtitle
        subtitle_text = self.style_config.get("subtitle", "Comprehensive User Guide & Technical Documentation")
        p_sub = self.doc.add_paragraph()
        run_sub = p_sub.add_run(subtitle_text)
        run_sub.font.name = self.font_name
        run_sub.font.size = Pt(13)
        run_sub.font.italic = True
        run_sub.font.color.rgb = RGBColor(120, 120, 120)

        # Push metadata to bottom
        for _ in range(8):
            self.doc.add_paragraph()

        # Metadata block at bottom
        p_meta = self.doc.add_paragraph()
        p_meta.paragraph_format.line_spacing = 1.2
        
        ver_run = p_meta.add_run("DOCUMENT VERSION: ")
        ver_run.font.bold = True
        ver_run.font.size = Pt(9)
        ver_run.font.color.rgb = RGBColor(100, 100, 100)
        
        p_meta.add_run("1.0 (Official Draft)\n")
        
        date_run = p_meta.add_run("PUBLISHED DATE:   ")
        date_run.font.bold = True
        date_run.font.size = Pt(9)
        date_run.font.color.rgb = RGBColor(100, 100, 100)
        
        import datetime
        current_date = datetime.datetime.now().strftime("%B %Y")
        p_meta.add_run(f"{current_date}\n")
        
        auth_run = p_meta.add_run("GENERATED BY:     ")
        auth_run.font.bold = True
        auth_run.font.size = Pt(9)
        auth_run.font.color.rgb = RGBColor(100, 100, 100)
        p_meta.add_run("Documentation Automation Engine")

        self.doc.add_page_break()

    def add_divider_page(self, title: str, description: str = ""):
        """Creates a professional section divider page for a module."""
        for _ in range(6):
            self.doc.add_paragraph()

        # Large Section Heading
        p_sec = self.doc.add_paragraph()
        p_sec.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run_sec = p_sec.add_run(title)
        run_sec.font.name = self.font_name
        run_sec.font.size = Pt(24)
        run_sec.font.bold = True
        run_sec.font.color.rgb = hex_to_rgb(self.primary_hex)

        # Horizontal Divider line
        p_line = self.doc.add_paragraph()
        p_line.alignment = WD_ALIGN_PARAGRAPH.CENTER
        self.add_bottom_border_to_paragraph(p_line, color_hex=self.secondary_hex, sz=12)

        # Optional short description
        if description:
            p_desc = self.doc.add_paragraph()
            p_desc.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run_desc = p_desc.add_run(description)
            run_desc.font.name = self.font_name
            run_desc.font.size = Pt(11)
            run_desc.font.italic = True
            run_desc.font.color.rgb = RGBColor(110, 110, 110)

        self.doc.add_page_break()

    def add_revision_history(self):
        """Creates the revision control table styled to corporate brand."""
        h = self.doc.add_heading(level=1)
        run = h.add_run("Revision History")
        run.font.name = self.font_name
        run.font.color.rgb = hex_to_rgb(self.primary_hex)
        
        table = self.doc.add_table(rows=2, cols=5)
        table.autofit = False
        self.set_table_borders(table, "E2E8F0")

        # Column widths
        table.columns[0].width = Inches(0.8) # Revision No.
        table.columns[1].width = Inches(1.1) # Date
        table.columns[2].width = Inches(1.4) # Author
        table.columns[3].width = Inches(1.4) # Approved By
        table.columns[4].width = Inches(1.8) # Description

        headers = ['Ver.', 'Date', 'Author', 'Approved By', 'Details of Changes']
        hdr_cells = table.rows[0].cells
        for idx, text in enumerate(headers):
            hdr_cells[idx].text = text
            self.set_cell_background(hdr_cells[idx], self.primary_hex)
            self.set_cell_margins(hdr_cells[idx], top=100, bottom=100, left=120, right=120)
            
            p = hdr_cells[idx].paragraphs[0]
            p.alignment = WD_ALIGN_PARAGRAPH.LEFT
            r = p.runs[0]
            r.font.name = self.font_name
            r.font.size = Pt(9.5)
            r.font.bold = True
            r.font.color.rgb = RGBColor(255, 255, 255)

        import datetime
        current_date = datetime.datetime.now().strftime("%Y-%m-%d")
        
        row_cells = table.rows[1].cells
        row_cells[0].text = "1.0"
        row_cells[1].text = current_date
        row_cells[2].text = "Automation Bot"
        row_cells[3].text = "Quality Lead"
        row_cells[4].text = "Generated corporate client manual."
        
        for idx in range(5):
            self.set_cell_margins(row_cells[idx], top=100, bottom=100, left=120, right=120)
            p = row_cells[idx].paragraphs[0]
            if p.runs:
                p.runs[0].font.name = self.font_name
                p.runs[0].font.size = Pt(9)

        self.doc.add_page_break()

    def add_toc_placeholder(self):
        """Adds a Table of Contents placeholder styled with native MS Word TOC fields."""
        h = self.doc.add_heading(level=1)
        run = h.add_run("Table of Contents")
        run.font.name = self.font_name
        run.font.color.rgb = hex_to_rgb(self.primary_hex)
        
        # Add descriptive text
        p_desc = self.doc.add_paragraph()
        run_desc = p_desc.add_run("This Table of Contents is dynamically generated using native Microsoft Word index fields. Please right-click the block below and select 'Update Field' to refresh page numbers.")
        run_desc.font.size = Pt(9.5)
        run_desc.font.italic = True
        run_desc.font.color.rgb = RGBColor(110, 110, 110)
        p_desc.paragraph_format.space_after = Pt(12)

        p_toc = self.doc.add_paragraph()
        self.add_toc_field(p_toc)
        
        self.doc.add_page_break()

    def add_callout(self, text: str, callout_type: str = "note"):
        """Adds a professional left-bordered callout box to emphasize text."""
        # Convert type to formatting colors
        types = {
            "warning": {"color": "DC2626", "bg": "FEF2F2", "title": "WARNING"},
            "important": {"color": "D97706", "bg": "FFFBEB", "title": "IMPORTANT"},
            "note": {"color": self.primary_hex, "bg": "F8FAFC", "title": "NOTE"}
        }
        cfg = types.get(callout_type.lower(), types["note"])
        
        # Create a single cell table
        table = self.doc.add_table(rows=1, cols=1)
        table.autofit = False
        table.columns[0].width = Inches(6.0)
        
        cell = table.cell(0, 0)
        self.set_cell_background(cell, cfg["bg"])
        self.set_cell_left_border(cell, cfg["color"], size_sz=36)
        self.set_cell_margins(cell, top=140, bottom=140, left=180, right=140)
        
        p = cell.paragraphs[0]
        p.paragraph_format.space_after = Pt(2)
        
        # Add Callout Title
        run_title = p.add_run(f"{cfg['title']}: ")
        run_title.font.name = self.font_name
        run_title.font.bold = True
        run_title.font.size = Pt(10)
        run_title.font.color.rgb = hex_to_rgb(cfg["color"])
        
        # Add Callout Content
        run_text = p.add_run(text)
        run_text.font.name = self.font_name
        run_text.font.italic = True
        run_text.font.size = Pt(9.5)
        run_text.font.color.rgb = hex_to_rgb(self.text_hex)
        
        # Spacer paragraph after the table
        p_space = self.doc.add_paragraph()
        p_space.paragraph_format.space_before = Pt(4)
        p_space.paragraph_format.space_after = Pt(4)

    def add_screen_section(self, screen_index: int, image_path: Path, content_data: Dict[str, Any]):
        """Renders a structured screen section with custom header, footer, image, and description table."""
        logo_val = self.style_config.get("logo_path", "")
        logo_path = Path(logo_val) if logo_val else None
        
        doc_title = self.style_config.get("company_name", "System Documentation") + " Manual"
        self.setup_header_footer(logo_path, doc_title, self.font_name)

        # Heading 1
        h = self.doc.add_heading(level=1)
        title_text = f"Screen {screen_index}: Interface Details"
        run = h.add_run(title_text)
        run.font.name = self.font_name
        run.font.color.rgb = hex_to_rgb(self.primary_hex)
        self.add_bottom_border_to_paragraph(h, color_hex=self.secondary_hex, sz=6)

        # Screen image
        if image_path.exists():
            # Add spacer
            p_space = self.doc.add_paragraph()
            p_space.paragraph_format.space_before = Pt(6)
            
            p_img = self.doc.add_paragraph()
            p_img.alignment = WD_ALIGN_PARAGRAPH.CENTER
            p_img.add_run().add_picture(str(image_path), width=Inches(5.8))
            
            cap = self.doc.add_paragraph(f"Figure {screen_index}: User Interface Screen Layout")
            cap.alignment = WD_ALIGN_PARAGRAPH.CENTER
            cap.style = 'Caption'
            cap.paragraph_format.space_after = Pt(12)

        # Procedure Prose
        prose = content_data.get("procedure_prose", "")
        if prose:
            h2 = self.doc.add_heading(level=2)
            r2 = h2.add_run("Step-by-Step Instructions")
            r2.font.name = self.font_name
            r2.font.color.rgb = hex_to_rgb(self.secondary_hex)
            
            # Format procedure steps
            for line in prose.split('\n'):
                line = line.strip()
                if not line:
                    continue
                
                # Check if this line is an alert/callout
                line_lower = line.lower()
                if any(x in line_lower for x in ["note:", "warning:", "important:"]):
                    # Parse type and clean line
                    c_type = "note"
                    clean_text = line
                    if "warning:" in line_lower:
                        c_type = "warning"
                        clean_text = line.split("Warning:", 1)[1].strip()
                    elif "important:" in line_lower:
                        c_type = "important"
                        clean_text = line.split("Important:", 1)[1].strip()
                    elif "note:" in line_lower:
                        c_type = "note"
                        clean_text = line.split("Note:", 1)[1].strip()
                    
                    self.add_callout(clean_text, callout_type=c_type)
                else:
                    # Regular body paragraph
                    p = self.doc.add_paragraph()
                    p.paragraph_format.line_spacing = 1.15
                    p.paragraph_format.space_after = Pt(6)
                    r = p.add_run(line)
                    r.font.name = self.font_name
                    
            self.doc.add_paragraph()

        # Element Descriptions Table
        fields = content_data.get("field_descriptions", [])
        if fields:
            h3 = self.doc.add_heading(level=2)
            r3 = h3.add_run("Interface Element Dictionary")
            r3.font.name = self.font_name
            r3.font.color.rgb = hex_to_rgb(self.secondary_hex)
            h3.paragraph_format.space_after = Pt(8)

            table = self.doc.add_table(rows=1, cols=2)
            table.autofit = False
            self.set_table_borders(table, "E2E8F0")

            table.columns[0].width = Inches(2.2) # Field name
            table.columns[1].width = Inches(4.3) # Description

            hdr_cells = table.rows[0].cells
            hdr_cells[0].text = 'User Interface Element'
            hdr_cells[1].text = 'Purpose & Functional Action'
            
            for idx in range(2):
                self.set_cell_background(hdr_cells[idx], self.primary_hex)
                self.set_cell_margins(hdr_cells[idx], top=120, bottom=120, left=150, right=150)
                p = hdr_cells[idx].paragraphs[0]
                r = p.runs[0]
                r.font.name = self.font_name
                r.font.size = Pt(9.5)
                r.font.bold = True
                r.font.color.rgb = RGBColor(255, 255, 255)

            # Insert zebra-striped rows
            for r_idx, field in enumerate(fields):
                row_cells = table.add_row().cells
                row_cells[0].text = field.get("field_name", "Unnamed Element")
                row_cells[1].text = field.get("description", "No description provided.")
                
                # Zebra striping: shade odd rows
                fill_color = "F8FAFC" if r_idx % 2 == 1 else "FFFFFF"
                
                for c in row_cells:
                    self.set_cell_background(c, fill_color)
                    self.set_cell_margins(c, top=100, bottom=100, left=150, right=150)
                    p = c.paragraphs[0]
                    if p.runs:
                        p.runs[0].font.name = self.font_name
                        p.runs[0].font.size = Pt(9)
                        p.runs[0].font.color.rgb = hex_to_rgb(self.text_hex)

            p_end = self.doc.add_paragraph()
            p_end.paragraph_format.space_before = Pt(8)

        self.doc.add_page_break()
