"""
Cover page renderer.

Spec B3: Remove 'Generated by: Documentation Automation Bot v2'.
Spec B2: Fail-loud if required fields are missing.
Spec D3: Cover disabled when manifest.cover_enabled is False.
"""

import datetime
from pathlib import Path
from typing import Any, Dict

from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from manual_builder.utils import (
    set_cell_background, set_cell_margins, set_table_borders,
    remove_table_borders, hex_to_rgb, add_bottom_border,
)
from manual_builder.build_error import BuildError


def render_cover(doc, section_entry, manifest, style):
    """
    Renders the client cover page.

    Skips entirely when ``manifest.cover_enabled`` is False (Spec D3).
    Raises BuildError if any required field is missing (Spec B2).
    """
    # D3: honour cover_enabled flag
    if not manifest.cover_enabled:
        return

    # B2: validate required cover fields
    client_display_name = manifest.client_display_name
    if not client_display_name or client_display_name.strip().startswith("["):
        raise BuildError("manifest field 'client_display_name' is required by the cover renderer")

    system_name = manifest.system_name or manifest.manual_title or ""

    # Load optional cover.yaml override data
    cover_data = {}
    if section_entry.source:
        cover_path = manifest.get_source_path(section_entry.source)
        if cover_path.exists():
            import yaml
            with cover_path.open("r", encoding="utf-8") as f:
                cover_data = yaml.safe_load(f) or {}

    document_title = cover_data.get("document_title", "User Manual")
    audience_line = f"For {manifest.audience}" if manifest.audience else ""
    version_value = manifest.document_version or manifest.version or "1.0"
    confidentiality = manifest.confidentiality or "CONFIDENTIAL"

    cover_style = style.cover
    layout = cover_style.get("layout", "centered")
    accent_color = style.get_color(cover_style.get("accent_bar_color", "primary"))
    title_size_pt = cover_style.get("title_size_pt", 28)
    subtitle_size_pt = cover_style.get("subtitle_size_pt", 16)

    # ── Top accent bar ────────────────────────────────────────────────────
    accent_table = doc.add_table(rows=1, cols=1)
    accent_table.autofit = False
    from docx.shared import Inches as _Inches
    accent_table.columns[0].width = _Inches(6.5)
    accent_cell = accent_table.cell(0, 0)
    set_cell_background(accent_cell, accent_color)
    set_cell_margins(accent_cell, top=300, bottom=300, left=150, right=150)
    accent_cell.paragraphs[0].paragraph_format.space_after = Pt(0)

    # ── Spacer ────────────────────────────────────────────────────────────
    for _ in range(2):
        doc.add_paragraph()

    # ── Client Logo ───────────────────────────────────────────────────────
    logo_path_str = style.logo.get("path", "")
    logo_path = Path(logo_path_str) if logo_path_str else None
    if logo_path and logo_path.exists():
        p_logo = doc.add_paragraph()
        p_logo.alignment = WD_ALIGN_PARAGRAPH.CENTER
        try:
            p_logo.add_run().add_picture(str(logo_path), height=Inches(1.0))
        except Exception:
            pass

    doc.add_paragraph()  # spacer

    # ── Audience line (e.g. "For State Nodal Officers") ───────────────────
    if audience_line:
        p_aud = doc.add_paragraph()
        p_aud.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r_aud = p_aud.add_run(audience_line)
        r_aud.font.name = style.heading_font
        r_aud.font.size = Pt(11)
        r_aud.font.italic = True
        r_aud.font.color.rgb = hex_to_rgb(style.get_color("muted"))

    # ── Client display name (small caps style) ────────────────────────────
    p_client = doc.add_paragraph()
    p_client.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r_client = p_client.add_run(client_display_name.upper())
    r_client.font.name = style.heading_font
    r_client.font.size = Pt(11)
    r_client.font.bold = False
    r_client.font.color.rgb = hex_to_rgb(style.get_color("muted"))

    # ── System name (Title style — large) ────────────────────────────────
    if system_name:
        p_sys = doc.add_paragraph()
        p_sys.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r_sys = p_sys.add_run(system_name)
        r_sys.font.name = style.heading_font
        r_sys.font.size = Pt(title_size_pt)
        r_sys.font.bold = True
        r_sys.font.color.rgb = hex_to_rgb(style.get_color("primary"))
        add_bottom_border(p_sys, color_hex=style.get_color("secondary"), sz=18)

    # ── Document title ("User Manual", 16pt italic) ───────────────────────
    p_title = doc.add_paragraph()
    p_title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r_title = p_title.add_run(document_title)
    r_title.font.name = style.heading_font
    r_title.font.size = Pt(subtitle_size_pt)
    r_title.font.italic = True
    r_title.font.color.rgb = hex_to_rgb(style.get_color("secondary"))

    # ── Push metadata block to bottom ────────────────────────────────────
    for _ in range(6):
        doc.add_paragraph()

    # ── Bottom divider ────────────────────────────────────────────────────
    p_line = doc.add_paragraph()
    add_bottom_border(p_line, color_hex=style.get_color("primary"), sz=12)
    p_line.paragraph_format.space_after = Pt(8)

    # ── Metadata table: Version | Published Date | Confidentiality ────────
    meta_table = doc.add_table(rows=1, cols=2)
    meta_table.autofit = False
    meta_table.columns[0].width = Inches(3.25)
    meta_table.columns[1].width = Inches(3.25)
    set_table_borders(meta_table, "E2E8F0")

    left_cell = meta_table.cell(0, 0)
    set_cell_background(left_cell, "F8FAFC")
    set_cell_margins(left_cell, top=120, bottom=120, left=150, right=150)
    p_left = left_cell.paragraphs[0]
    p_left.paragraph_format.line_spacing = 1.5

    # B3: no "Generated by" — replaced with Version / Date / Prepared By
    metadata_items = [
        ("DOCUMENT VERSION", version_value),
        ("PUBLISHED DATE", datetime.datetime.now().strftime("%d-%m-%Y")),
        ("PREPARED BY", manifest.prepared_by or "—"),
        ("REVIEWED BY", manifest.reviewed_by or "—"),
        ("APPROVED BY", manifest.approved_by or "—"),
    ]

    for label, val in metadata_items:
        r_lbl = p_left.add_run(f"{label}:\n")
        r_lbl.font.name = style.body_font
        r_lbl.font.size = Pt(8.5)
        r_lbl.font.bold = True
        r_lbl.font.color.rgb = RGBColor(100, 100, 100)
        r_val = p_left.add_run(f"{val}\n\n")
        r_val.font.name = style.body_font
        r_val.font.size = Pt(9.5)
        r_val.font.color.rgb = RGBColor(40, 40, 40)

    right_cell = meta_table.cell(0, 1)
    set_cell_background(right_cell, style.get_color("primary"))
    set_cell_margins(right_cell, top=120, bottom=120, left=150, right=150)
    p_right = right_cell.paragraphs[0]
    p_right.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p_right.paragraph_format.space_before = Pt(24)
    r_conf = p_right.add_run(confidentiality)
    r_conf.font.name = style.heading_font
    r_conf.font.size = Pt(11)
    r_conf.font.bold = True
    r_conf.font.color.rgb = RGBColor(255, 255, 255)

    doc.add_page_break()
